name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Firebase login
        run: firebase login --no-localhost --token ${{ b33d8bc1d78a419b78c9403ae7689d683fb621c3 }}

      - name: Deploy to Firebase
        run: firebase deploy --only hosting --token ${{ b33d8bc1d78a419b78c9403ae7689d683fb621c3 }} --public main
